services:
  - type: web
    name: failureaware-ai
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn app.api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: GEMINI_API_KEY
        sync: false
